--Magnitude
--Total sales by country
SELECT
	dim_cust.country country_name,
	SUM(f_sales.sales_amount) total_sales
FROM
	DataWarehouse.gold.fact_sales f_sales
LEFT JOIN DataWarehouse.gold.dim_customers dim_cust
ON f_sales.customer_key = dim_cust.customer_key
GROUP BY dim_cust.country;
-- Find total customers by countries
SELECT
	dim_cust.country country,
	COUNT(dim_cust.customer_id) total_of_customers
FROM
	DataWarehouse.gold.dim_customers dim_cust
GROUP BY 
	dim_cust.country;
	
-- Find total customers by gender
SELECT
	dim_cust.gender gender,
	COUNT(dim_cust.customer_id) total_of_customers
FROM
	DataWarehouse.gold.dim_customers dim_cust
GROUP BY 
	dim_cust.gender;
-- Find total products by category
SELECT
	dim_prd.category category,
	COUNT(dim_prd.category_id) count_of_product_by_category
FROM
	DataWarehouse.gold.dim_products dim_prd
GROUP BY
	dim_prd.category;
-- What is the average cost in each category?
SELECT
	dim_prd.category category,
	AVG(dim_prd.cost) avg_cost_by_category
FROM
	DataWarehouse.gold.dim_products dim_prd
GROUP BY
	dim_prd.category;
-- What is the total revenue generated for each category?
SELECT
	dim_prd.category,
	SUM(f_sales.sales_amount)
FROM
	DataWarehouse.gold.fact_sales f_sales
LEFT JOIN
	DataWarehouse.gold.dim_products dim_prd
ON 
	f_sales.product_key = dim_prd.product_key
GROUP BY
	dim_prd.category;


-- Find total revenue is generated by each customer
SELECT
	dim_cust.first_name,
	SUM(f_sales.sales_amount)
FROM
	DataWarehouse.gold.fact_sales f_sales
LEFT JOIN
	DataWarehouse.gold.dim_customers dim_cust
ON 
	f_sales.customer_key = dim_cust.customer_key
GROUP BY
	dim_cust.first_name
	;
-- What is the distirbution of sold items across countries?	
SELECT
	dim_cust.country,
	SUM(f_sales.sales_amount)
FROM
	DataWarehouse.gold.fact_sales f_sales
LEFT JOIN
	DataWarehouse.gold.dim_customers dim_cust
ON 
	f_sales.customer_key = dim_cust.customer_key
GROUP BY
	dim_cust.country;
